version: '3.1'

services:
  wordpress:
    image: wordpress:php8.3-fpm
    container_name: ${COMPOSE_PROJECT_NAME}-wordpress
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    networks:
      - network
    depends_on:
      - db
    environment:
      - WORDPRESS_DB_HOST=${WORDPRESS_DB_HOST}
      - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}
      - WORDPRESS_DB_USER=${WORDPRESS_DB_USER}
      - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD}
    volumes:
      - ${WORDPRESS_LOCAL_HOME}:/var/www/html

  db:
    image: mysql:8.0
    container_name: ${COMPOSE_PROJECT_NAME}-database
    env_file:
      - .env
    restart: always
    networks:
      - network
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ${MYSQL_LOCAL_HOME}:/var/lib/mysql
    command:
      - '--default-authentication-plugin=mysql_native_password'

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    links:
      - db:db
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD},
      UPLOAD_LIMIT: 10000000000
    ports:
      - ${PMA_PORT}:80
    networks:
      - network
  nginx:
    image: nginx:1
    container_name: ${COMPOSE_PROJECT_NAME}-nginx
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - network
    depends_on:
      - wordpress
    ports:
      - ${WEB_HOST_PORT}:${WEB_DOCKER_PORT}    # http
    volumes:
      - ${WORDPRESS_LOCAL_HOME}:/var/www/html
      - ${NGINX_CONF}:/etc/nginx/conf.d/default.conf
      - ${NGINX_SSL_CERTS}:/etc/ssl:ro
      - ${NGINX_LOGS}:/var/log/nginx
  wpcli:
    image: wordpress:cli
    depends_on:
        - wordpress
        - db
    links:
      - db:db
      - wordpress
    user: 1000:1000
    command: tail -f /dev/null
    container_name: ${COMPOSE_PROJECT_NAME}_wpcli
    env_file:
      - .env
    networks:
        - network
    environment:
      - WORDPRESS_DB_HOST=${WORDPRESS_DB_HOST}
      - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}
      - WORDPRESS_DB_USER=${WORDPRESS_DB_USER}
      - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD}
    volumes:
      - ${WORDPRESS_DATA_DIR:-./wordpress}:/var/www/html
    working_dir: /var/www/html

networks:
  network:
    driver: bridge
